name: Build APK

on:
  push:
    branches:
      - main # Укажите вашу основную ветку
  pull_request:
    branches:
      - main # Укажите вашу основную ветку

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '9' # Укажите нужную версию JDK

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build the project
        run: ./gradlew assembleDebug # Или ./gradlew assembleRelease для релизной версии

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: my-app-apk
          path: app/build/outputs/apk/debug/app-debug.apk # Укажите путь к вашему APK
